import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { meetingMinutesTable } from "@workspace/db/schema";
import { eq, desc } from "drizzle-orm";
import PDFDocument from "pdfkit";
import { createTransporter, getSenderAddress } from "../emailClient";

const router: IRouter = Router();

function genCode(id: number) {
  return "MM-" + String(id).padStart(3, "0");
}

function generatePDF(minutes: typeof meetingMinutesTable.$inferSelect): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const primaryColor = "#1a1a2e";
    const accentColor = "#e63946";

    doc.fontSize(18).fillColor(primaryColor).font("Helvetica-Bold")
      .text("JOINT HEALTH & SAFETY COMMITTEE", { align: "center" });
    doc.fontSize(14).text("Meeting Minutes", { align: "center" });
    doc.fontSize(11).fillColor("#555")
      .text("Unifor Local 1285 — Saputo Georgetown", { align: "center" });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(accentColor);
    doc.moveDown(0.5);

    doc.font("Helvetica-Bold").fillColor(primaryColor).fontSize(11).text("Meeting Details");
    doc.font("Helvetica").fillColor("#333").fontSize(10);
    doc.text(`Record Code: ${minutes.minutesCode}`);
    doc.text(`Meeting Date: ${minutes.meetingDate}`);
    doc.text(`Meeting Type: ${minutes.meetingType}`);
    if (minutes.nextMeetingDate) doc.text(`Next Meeting: ${minutes.nextMeetingDate}`);
    doc.moveDown(0.5);

    const mgmt = (minutes.managementAttendees as any[]) || [];
    const workers = (minutes.workerAttendees as any[]) || [];

    if (mgmt.length > 0) {
      doc.font("Helvetica-Bold").text("Management Attendees:");
      doc.font("Helvetica");
      mgmt.forEach((a) => doc.text(`  • ${a.name} — ${a.title}`));
      doc.moveDown(0.3);
    }
    if (workers.length > 0) {
      doc.font("Helvetica-Bold").text("Worker Attendees:");
      doc.font("Helvetica");
      workers.forEach((a) => doc.text(`  • ${a.name} — ${a.title}`));
      doc.moveDown(0.3);
    }

    const agenda = (minutes.agendaItems as any[]) || [];
    if (agenda.length > 0) {
      doc.moveDown(0.3);
      doc.font("Helvetica-Bold").fontSize(11).text("Agenda Items");
      doc.font("Helvetica").fontSize(10);
      agenda.forEach((item, i) => {
        doc.font("Helvetica-Bold").text(`${i + 1}. ${item.topic}`);
        if (item.notes) doc.font("Helvetica").text(`   ${item.notes}`);
      });
      doc.moveDown(0.3);
    }

    const motions = (minutes.motions as string[]) || [];
    if (motions.length > 0) {
      doc.font("Helvetica-Bold").fontSize(11).text("Motions Made");
      doc.font("Helvetica").fontSize(10);
      motions.forEach((m) => doc.text(`  • ${m}`));
      doc.moveDown(0.3);
    }

    if (minutes.decisions) {
      doc.font("Helvetica-Bold").fontSize(11).text("Decisions Reached");
      doc.font("Helvetica").fontSize(10).text(minutes.decisions);
      doc.moveDown(0.3);
    }

    const actionItems = (minutes.actionItems as any[]) || [];
    if (actionItems.length > 0) {
      doc.font("Helvetica-Bold").fontSize(11).text("Action Items Assigned");
      doc.font("Helvetica").fontSize(10);
      actionItems.forEach((a) => doc.text(`  • ${a.title} — Assigned to: ${a.assignedTo}, Due: ${a.dueDate}`));
      doc.moveDown(0.3);
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#ccc");
    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(10).text("Signatures", { align: "center" });
    doc.moveDown();

    const sigY = doc.y;
    doc.font("Helvetica").fontSize(9);
    doc.text("Worker Co-Chair:", 50, sigY);
    doc.text("_________________________________", 50, sigY + 15);
    doc.text(minutes.workerCoChairSigned ? "✓ Signed" : "(Not yet signed)", 50, sigY + 32);

    doc.text("Management Co-Chair:", 300, sigY);
    doc.text("_________________________________", 300, sigY + 15);
    doc.text(minutes.managementCoChairSigned ? "✓ Signed" : "(Not yet signed)", 300, sigY + 32);

    doc.moveDown(3);
    doc.fontSize(8).fillColor("#aaa").text(
      `Generated by JHSC Co-Chair Tracker — OHSA s.9(33) — ${new Date().toLocaleDateString("en-CA")}`,
      { align: "center" }
    );

    doc.end();
  });
}

router.get("/", async (req, res) => {
  try {
    const items = await db.select().from(meetingMinutesTable).orderBy(desc(meetingMinutesTable.meetingDate));
    res.json(items);
  } catch (err) {
    req.log.error({ err }, "Failed to list meeting minutes");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/", async (req, res) => {
  try {
    const [created] = await db
      .insert(meetingMinutesTable)
      .values({ ...req.body, minutesCode: "MM-000" })
      .returning();

    const [updated] = await db
      .update(meetingMinutesTable)
      .set({ minutesCode: genCode(created.id) })
      .where(eq(meetingMinutesTable.id, created.id))
      .returning();

    res.status(201).json(updated);
  } catch (err) {
    req.log.error({ err }, "Failed to create meeting minutes");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/:id", async (req, res) => {
  try {
    const [item] = await db.select().from(meetingMinutesTable).where(eq(meetingMinutesTable.id, parseInt(req.params.id)));
    if (!item) return res.status(404).json({ error: "Not found" });
    res.json(item);
  } catch (err) {
    req.log.error({ err }, "Failed to get meeting minutes");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.put("/:id", async (req, res) => {
  try {
    const [updated] = await db
      .update(meetingMinutesTable)
      .set({ ...req.body, updatedAt: new Date() })
      .where(eq(meetingMinutesTable.id, parseInt(req.params.id)))
      .returning();
    if (!updated) return res.status(404).json({ error: "Not found" });
    res.json(updated);
  } catch (err) {
    req.log.error({ err }, "Failed to update meeting minutes");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    await db.delete(meetingMinutesTable).where(eq(meetingMinutesTable.id, parseInt(req.params.id)));
    res.json({ success: true });
  } catch (err) {
    req.log.error({ err }, "Failed to delete meeting minutes");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/:id/pdf", async (req, res) => {
  try {
    const [item] = await db.select().from(meetingMinutesTable).where(eq(meetingMinutesTable.id, parseInt(req.params.id)));
    if (!item) return res.status(404).json({ error: "Not found" });

    const pdf = await generatePDF(item);
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="minutes-${item.minutesCode}.pdf"`);
    res.send(pdf);
  } catch (err) {
    req.log.error({ err }, "Failed to generate PDF");
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});

router.post("/:id/email", async (req, res) => {
  try {
    const [item] = await db.select().from(meetingMinutesTable).where(eq(meetingMinutesTable.id, parseInt(req.params.id)));
    if (!item) return res.status(404).json({ error: "Not found" });

    const { recipientEmail } = req.body;
    if (!recipientEmail) return res.status(400).json({ error: "recipientEmail is required" });

    const pdf = await generatePDF(item);
    const transporter = createTransporter();
    const from = getSenderAddress();

    await transporter.sendMail({
      from,
      to: recipientEmail,
      subject: `JHSC Meeting Minutes — ${item.meetingDate} (${item.minutesCode})`,
      html: `
        <p>Please find attached the JHSC meeting minutes for <strong>${item.meetingDate}</strong>.</p>
        <p>Meeting Type: ${item.meetingType}</p>
        <p>Record: ${item.minutesCode}</p>
        <br>
        <p>This document is required under OHSA s.9(33). Please retain for your records.</p>
        <p><em>JHSC Co-Chair Tracker — Unifor Local 1285 / Saputo Georgetown</em></p>
      `,
      attachments: [
        {
          filename: `minutes-${item.minutesCode}.pdf`,
          content: pdf,
          contentType: "application/pdf",
        },
      ],
    });

    await db
      .update(meetingMinutesTable)
      .set({ emailedAt: new Date(), updatedAt: new Date() })
      .where(eq(meetingMinutesTable.id, item.id));

    res.json({ success: true });
  } catch (err) {
    req.log.error({ err }, "Failed to email meeting minutes");
    res.status(500).json({ error: "Failed to send email" });
  }
});

export default router;
